name: pork_manager_mobile
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.3
  http_parser: ^4.0.0
  shared_preferences: ^2.0.0
  logger: ^2.3.0
  intl: ^0.17.0
  image_picker: ^0.8.4+4
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

android:
  package: com.example.myapp
